modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Bannerok"
description='''${mod_description}'''

[[mixins]]
config="millenaire-universalis.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="millenaire"
type="required"
reason="Millenaire Universalis targets Millenaire ${millenaire_version} on Minecraft ${minecraft_version}."
versionRange="${millenaire_version_range}"
ordering="AFTER"
side="BOTH"
