{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.kaiserroman.millenaire",
    "module": "millenaire-simulation",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "millenaire-simulation-1.0.0.jar",
          "url": "millenaire-simulation-1.0.0.jar",
          "size": 64592,
          "sha512": "df5f3d17efaedaf70f1867093ea137e99f3705120fb73e7d479506d577160e4e0a414ab73b1d7ac43714f89617d6d7d01fa28ddb901b5c830030d5fc98892170",
          "sha256": "28cb49b4e985ed4216d01fa8642d12df9471f9c459e8e38d2edea9bc97a0b008",
          "sha1": "a4a62f54112c4eef4b28213577f1b03cb08427b0",
          "md5": "014bc76ef3c2254e84491af497e3a684"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "millenaire-simulation-1.0.0.jar",
          "url": "millenaire-simulation-1.0.0.jar",
          "size": 64592,
          "sha512": "df5f3d17efaedaf70f1867093ea137e99f3705120fb73e7d479506d577160e4e0a414ab73b1d7ac43714f89617d6d7d01fa28ddb901b5c830030d5fc98892170",
          "sha256": "28cb49b4e985ed4216d01fa8642d12df9471f9c459e8e38d2edea9bc97a0b008",
          "sha1": "a4a62f54112c4eef4b28213577f1b03cb08427b0",
          "md5": "014bc76ef3c2254e84491af497e3a684"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "millenaire-simulation-1.0.0-sources.jar",
          "url": "millenaire-simulation-1.0.0-sources.jar",
          "size": 30888,
          "sha512": "a01ea300a8be8c1cd6e93612867f34f7a15ed8a0389585bf2ce122b54444ba71070466e664c87d6112ff31697a431ea5ecb986d42018586d98e30d1df9454da1",
          "sha256": "0368053e940a54d3bf800e5a3222f2d3535d042794ca8337287210d833e0969c",
          "sha1": "8534daaaadb2c1c26a78c73c6e9ef3b4511bead6",
          "md5": "f70b5e7a382201188d42e41cb6799de7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "millenaire-simulation-1.0.0-javadoc.jar",
          "url": "millenaire-simulation-1.0.0-javadoc.jar",
          "size": 177361,
          "sha512": "3e8977d4a0b4c1bb9ccc5dbbf4e28980435bbb30b7cab3431aea914c92d6ce26853af5cce2abae46484eff52f9fa45da3a87c1b0e2ebe8bb683dc704fa177eb8",
          "sha256": "eaf98a145e3ac3515c8e13dbefdfd73a1b631a89998c1eb9a8a0dcf8b1e00c7d",
          "sha1": "760ddc70b8852ad503674d1077f5a23fabbe38a8",
          "md5": "82a32ca5d67ad318f4c9730c2aa2afbd"
        }
      ]
    }
  ]
}
