{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.kaiserroman.millenaire",
    "module": "millenaire-realm",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "millenaire-realm-1.0.0.jar",
          "url": "millenaire-realm-1.0.0.jar",
          "size": 104343,
          "sha512": "bf14c0b0097cd731f925fa809e7b91f1a7a1f7d5da399c16b8449bc418b3c609d4337f52b2dad2e88e2f0be86b9891a7551959e8bb7495856591d37534f26311",
          "sha256": "321dcfff7796f5326c6ea6e7343c17de2ff18305e90df4574dfab3b71829bd47",
          "sha1": "142a951044bdc201d283fbe362897b430eb47d49",
          "md5": "e3c190e33d4148b8a959ddf0ccc99f1b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "millenaire-realm-1.0.0.jar",
          "url": "millenaire-realm-1.0.0.jar",
          "size": 104343,
          "sha512": "bf14c0b0097cd731f925fa809e7b91f1a7a1f7d5da399c16b8449bc418b3c609d4337f52b2dad2e88e2f0be86b9891a7551959e8bb7495856591d37534f26311",
          "sha256": "321dcfff7796f5326c6ea6e7343c17de2ff18305e90df4574dfab3b71829bd47",
          "sha1": "142a951044bdc201d283fbe362897b430eb47d49",
          "md5": "e3c190e33d4148b8a959ddf0ccc99f1b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "millenaire-realm-1.0.0-sources.jar",
          "url": "millenaire-realm-1.0.0-sources.jar",
          "size": 49695,
          "sha512": "5b49def03a384bde6e9d5d88dd3c9e050f3626b40e925cacb61062e9157171d67737b7e002397efc172910d0386bba243251477ca4d3bae31e346fea6a1faca5",
          "sha256": "2b906c0dee4dd428fcd73a428927c870abef2ecd8e1423f86ab0d10f1e588231",
          "sha1": "752ae31c1a2cf95e12a211b8c9feb3373bdc61d1",
          "md5": "f630395a55661ec938fb76db67d6f199"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "millenaire-realm-1.0.0-javadoc.jar",
          "url": "millenaire-realm-1.0.0-javadoc.jar",
          "size": 275077,
          "sha512": "1632c699d29e43b2a33076ca1a56b4712619ec0598f31cc2896713ec3f37ee31333a976b38d6acb8e4a6d9265e862299612043759c93f21c82f4e00d90fe3f89",
          "sha256": "7f449b777a37a0ee4f25a51667992806a4712915d1ad526e82636ee17406ca1a",
          "sha1": "1cfeb8f10c50492467d3b393a7e4b80ad7194fad",
          "md5": "00c4bb7c87c4a35d6a2182d4e462333a"
        }
      ]
    }
  ]
}
